/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";var d=Object.defineProperty;var S=Object.getOwnPropertyDescriptor;var b=Object.getOwnPropertyNames;var w=Object.prototype.hasOwnProperty;var v=(r,t)=>{for(var e in t)d(r,e,{get:t[e],enumerable:!0})},C=(r,t,e,i)=>{if(t&&typeof t=="object"||typeof t=="function")for(let l of b(t))!w.call(r,l)&&l!==e&&d(r,l,{get:()=>t[l],enumerable:!(i=S(t,l))||i.enumerable});return r};var j=r=>C(d({},"__esModule",{value:!0}),r);var k={};v(k,{default:()=>a});module.exports=j(k);var s=require("obsidian"),a=class extends s.Plugin{async onload(){this.addCommand({id:"convert-csv-to-md-table",name:"Convert CSV selection to Markdown table",editorCallback:t=>{if(!t.somethingSelected()){new s.Notice("Select some CSV text first.");return}let e=t.getSelection(),i=this.csvToMarkdownTable(e);if(!i){new s.Notice("Selection is not valid CSV.");return}t.replaceSelection(i)}})}csvToMarkdownTable(t){let e=t.split(`
`).map(n=>n.trim()).filter(n=>n.length>0);if(e.length===0)return null;let i=e.map(n=>{let o=n.split(",").map(f=>f.trim());return o.length>1&&o[o.length-1]===""&&o.pop(),o}),l=Math.max(...i.map(n=>n.length)),p=n=>{let o=[...n];for(;o.length<l;)o.push("");return o},[c,...m]=i.map(p);if(!c)return null;let h=`| ${c.join(" | ")} |`,u=`| ${c.map(()=>"---").join(" | ")} |`,g=m.map(n=>`| ${n.join(" | ")} |`);return[h,u,...g].join(`
`)}};
